services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: ubqtdatabase
    ports:
    - "5432:5432"
    volumes: 
      - db:/var/lib/postgresql
  node_api_1:
    container_name: node_api_1
    build: ./nodejs_api
    environment:
      PORT: ${API_INSTANCE_1_PORT}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
    ports:
      - "${API_INSTANCE_1_PORT}:8000"
    depends_on:
      - db
  go_api_1:
    container_name: go_api_1
    build: ./go_api
    environment:
      PORT: ${API_INSTANCE_2_PORT}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
    ports:
      - "${API_INSTANCE_2_PORT}:8000"
    depends_on:
      - db
  python_api_1:
    build: ./python_api
    container_name: python_api_1
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:123456789@db:5432/ubqtdatabase
    ports:
      - "${API_INSTANCE_3_PORT}:8000"
    depends_on:
      - db
  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - db
      - node_api_1
      - go_api_1
      - python_api_1
volumes:
  db:
