services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: ubqtdatabase
    ports:
    - "5432:5432"
    volumes: 
      - db:/var/lib/postgresql
  node_api:
    container_name: node_api
    build: ./nodejs_api
    environment:
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
    ports:
        - ${PORT}:${PORT}
    depends_on:
        - db
  python_api:
    build: ./python_api
    container_name: python_api
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:123456789@db:5432/ubqtdatabase
    ports:
      - "3002:3002"
    depends_on:
      - db

volumes:
  db:
